application: kroman0cms-hrd
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /(login|logout|test)?
  script: cal.application
  secure: always

- url: /(genkeys|addkey)
  script: crypto.application
  login: admin
  secure: always

libraries:
- name: pycrypto
  version: "2.3"

env_variables:
  GAE_USE_SOCKETS_HTTPLIB: 'true'
